### ISSUE TITLE
Wrong path for CSS assets

### ISSUE THREAD

**Issue by ds-teck** [chialab/rna#118]
For the CSS assets generated by esbuild (included in the metafile, not as a <link rel="stylesheet">), the generated file path appears platform specific. When run on Windows, the path is a single backslash, which is not the standard (forward slash).
In the worst case, a path given to the "loadStyle" function is e.g. "static\index-23423.css", in which the single backslash actually produces a completely wrong path, preventing CSS from rendering in the browser.

Please always use forward slashes as path separators in the generated HTML.

By the way, why are CSS assets from the metafile included es loader scripts instead of a simple <link ...>?

The problem is in https://github.com/chialab/rna/blob/main/packages/esbuild-plugin-html/lib/collectScripts.js
Lines 110-111.

**Comment by edoardocavazza** [comment]
Thanks for reporting! I will look at this in the next week
