### ISSUE TITLE
Can't use assets in a SPA without proxy

### ISSUE THREAD

**Issue by ds-teck** [chialab/rna#119]
The problem is with the esbuild-html-plugin.
I have a script defined in my HTML entry point like this:
<script src="index.js></script>
The means that it gets transformed to something like:
<script src="index-234234.js></script>
If I use my app as a SPA, this script path is appended to the app's URL, like:
https://example.com/some/path/index-23434.js
whereas it should be in the root folder: https://example.com/index-23434.js
Currently the only way out is to use a proxy, which I don't want to.

The plugin should allow setting paths to assets like this:
<script src="/index.js></script> (with the forward slash, indicating that whatever name it eventually gets, it's always available from the root)
Currently the plugin just ignores such assets.

**Comment by edoardocavazza** [comment]
I will look at this, in the meantime I am wondering if using a [`<base href="/">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) in your `<head>` would fix the issue and if it would be a suitable solution for your SPA.
