### ISSUE TITLE
[esbuild-plugin-html] Load style files without script

### ISSUE THREAD

**Issue by tim-we** [chialab/rna#124]
When using the HTML plugin and I import styles in JS via
```js
import "path/to/style.css";
```
it results in an additional script tag added to the HTML:
```html
<script type="module">
        (function() {
            function loadStyle(url) {
                var l = document.createElement('link');
                l.rel = 'stylesheet';
                l.href = url;
                document.head.appendChild(l);
            }
            loadStyle('style.css');
        }());
</script>
```
Not sure what the reason for this is over just including it via a `<link>` tag directly, perhaps to avoid render blocking?
Anyway I would like to have at least an option to configure it s.t. this would just add
```html
<link rel="stylesheet" href="style.css"/>
```
because I want my styles to be render blocking (to avoid FOUC) and save some bytes.

The code responsible for this seems to be in [collectScripts.js](https://github.com/chialab/rna/blob/0ce0679e35955ec5bac5d1f9bc65cbe2f08c85a1/packages/esbuild-plugin-html/lib/collectScripts.js#L95-L116).
Happy to provide the PR for this change myself if you agree with this proposal.

Thanks for this plugin btw :)

**Comment by tim-we** [comment]
Thanks for your reply @edoardocavazza. Specifying the entry point in the HTML file like suggested is in option, however that means I have to manage all my CSS imports in the root CSS file. With the other approach I only get the CSS I need when every UI component/JS module imports only the CSS it requires. That's why I prefer that way of importing CSS, it's one way to avoid bloat that I don't have to think about.

> Our hope is that this issue will be fixed, so for now, we handle the CSS import, just as esbuild would, via javascript.

If you plan to drop that code eventually, I guess it doesn't make much sense to add options around that.

> This is an intended behavior: if you import the CSS via JavaScript, the output will continue to load the CSS via JavaScript.

This is a good point, I just wish there was a way around that.

**Comment by edoardocavazza** [comment]
In the next days I will try to find out the esbuild position on this. If I can't find a plan to fix the issue, I think it would make sense to introduce an option to get the optimised result.
