### ISSUE TITLE
Insert <link> directly, without an intermediate <script>

### ISSUE THREAD

**Issue by cowwoc** [chialab/rna#172]
Instead of inserting a `<script>` at https://github.com/chialab/rna/blob/6f5fefd50f39a82d7bd01106b54e4acb07cb8806/packages/esbuild-plugin-html/lib/collectScripts.js#L102 are you able to insert a `<link>` directly? This would look more natural, and it would add support for users who disable Javascript.

**Comment by edoardocavazza** [comment]
It is certainly possible. The reason why it doesn't work that way at the moment is that the plugin does not alter how the CSS file was included in the build:
* if it is imported via `<link>` in the HTML file, the plugin maintains the reference as `<link>`;
* If it is imported via script, the plugin replicates the import via script.

If I remember correctly, there have been concerns about this behavior in the past, which is definitely subject to review.

I would be interested in hearing your opinion on the reasoning above.

**Comment by cowwoc** [comment]
Concrete example of what I would like to do:

```
<link
  rel="stylesheet"
  media="(prefers-color-scheme:light)"
  href="@shoelace-style/shoelace/dist/themes/light.css"
/>
<link
  rel="stylesheet"
  media="(prefers-color-scheme:dark)"
  href="@shoelace-style/shoelace/dist/themes/dark.css"
  onload="document.documentElement.classList.add('sl-theme-dark');"
/>
<script type="module" src="@shoelace-style/shoelace/dist/shoelace.js"></script>
```

**Comment by cowwoc** [comment]
It turns out that this isn't just a nice-to-have feature. There is a concrete difference between adding a `<link>` programmatically and having it as part of the HTML in the first place: https://github.com/shoelace-style/shoelace/discussions/1910#discussioncomment-8685333

Bottom line: if I replace the JS code with an inline `<link>` the Flash of Unstyled Content goes away. It looks like the browser runs JS code after rendering the screen. By this point, it's too late to change the background color of the page without seeing a flash...

**Comment by cowwoc** [comment]
So to recap... We have the concept of injecting `<link>` at bundle-time or runtime. To avoid the FOUC we need to inject `<link>` at bundle-time.

If you can't think of any reason why anyone would want to inject styles at runtime, then I would recommend always injecting links at bundle-time.

If there is a valid use-case for runtime injection, then we should probably add an option that lets users decide one way or another.

**Comment by cowwoc** [comment]
I can confirm that importing from inside CSS files fixes my problem. I no longer get a flash of unstyled content because the `<link>` is being added at bundle-time. I love it! :)

I still think that users would be better off using bundle-time `<link>` in all cases, but that's just me.

That said, I don't think you even need an option any more. If users want bundle-time `<link>` they can just use CSS imports as you recommended. You could just document this and move on. Thanks a lot for your help! Feel free to close this issue when you're done.

**Comment by cowwoc** [comment]
Another thing I just discovered is that JS runs before the page is rendered, if and only if, the JS file does not contain any imports.

So I created a separate JS file without any imports that detects the user's dark mode preference and adds the necessary CSS class to the `<html>` tag. No more flash of white :)

**Comment by yaakovfeldman** [comment]
This feature would be great as the current behaviour (inline script) fails if you have a Content Security Policy.
