### ISSUE TITLE
How to use @chialab/esbuild-plugin-worker create web-workers?

### ISSUE THREAD

**Issue by okikio** [chialab/rna#22]
Quick question, I'd like to use `@chialab/esbuild-plugin-worker` together with `gulp-esbuild` as a plugin for loading workers, but I am not clear on how I'm supposed to do that. the docs don't mention how you create workers.

**Comment by edoardocavazza** [comment]
Hello @okikio! I have updated the [README file](https://github.com/chialab/rna/tree/main/packages/esbuild-plugin-worker) of the plugin with some information.

Please do not hesitate to ask questions or more examples, we are still setting up the ecosystem and things may be incomplete. Any feedback is appreciated.

**Comment by okikio** [comment]
Thanks for the quick response, but unfortunately I won't be able to use `@chialab/esbuild-plugin-worker`, as it lacks support for the `{ type: "module" }` option for my situation I was able to create a small custom solution. 

In my case, the main reason I need the `{ type: "module" }` is to avoid redundant/repetitive code, I was hoping to have modules required for both the main thread and the worker be loaded once, as the project I am working on (an online bundler) is rather complex. I appreciate you taking the time, and I can't wait to see what this project turns into. 

If you want to learn more about my project I suggest check out the repo [github.com/okikio/bundle](https://github.com/okikio/bundle) or the site itself [bundle.js.org](https://bundle.js.org)

**Comment by edoardocavazza** [comment]
I see. Supporting `{ type: "module" }` is quite easy, but at the moment there is not a way to emit chunks in esbuild, so the worker build cannot share code with the main build. We are looking forward for https://github.com/evanw/esbuild/issues/795 and https://github.com/evanw/esbuild/issues/312.

> If you want to learn more about my project I suggest check out the repo github.com/okikio/bundle or the site itself bundle.js.org

Sure I will!

**Comment by okikio** [comment]
Ok, thanks

**Comment by okikio** [comment]
It's been a while, does `@chialab/esbuild-plugin-worker` noe support module web-workers?

**Comment by edoardocavazza** [comment]
Hi @okikio. Some time ago I added a check for `type: 'module'` in Worker initialization. It *should* work, but I have to admit I had not test it so much. Would you like to do some testing?

**Comment by okikio** [comment]
I'll see if I can do some testing

**Comment by edoardocavazza** [comment]
Hello @okikio , any update on this? Can we close the issue?

**Comment by okikio** [comment]
Yeah,  thanks so much for your help
