### ISSUE TITLE
html plugin unexpected output with `outdir` option

### ISSUE THREAD

**Issue by ksmithut** [chialab/rna#25]
Here's my folder structure:

<details>
<summary><code>package.json</code></summary>

```json
{
  "name": "esbuild-html",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "type": "module",
  "devDependencies": {
    "@chialab/esbuild-plugin-html": "^0.11.19",
    "esbuild": "^0.12.20"
  }
}
```
</details>

<details>
<summary><code>src/index.html</code></summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Home</title>
  </head>
  <body>
    <h1>Home</h1>
    <script src="index.js" type="module"></script>
  </body>
</html>
```
</details>

<details>
<summary><code>src/index.js</code></summary>

```js
console.log('Home')
export {}
```
</details>

<details>
<summary><code>src/sub/index.html</code></summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Sub</title>
  </head>
  <body>
    <h1>Sub</h1>
    <script src="index.js" type="module"></script>
  </body>
</html>
```
</details>

<details>
<summary><code>src/sub/index.js</code></summary>

```js
console.log('Sub')
export {}
```
</details>

<details>
<summary><code>build.js</code></summary>

```js
import esbuild from 'esbuild'
import htmlPlugin from '@chialab/esbuild-plugin-html'

esbuild.build({
  entryPoints: ['./src/index.html', './src/sub/index.html'],
  outdir: './dist/',
  plugins: [htmlPlugin({})]
})
```
</details>

When I run `node build.js` I expect the resulting `dist` directory to look something like this:

```
dist/
├─ index.html
├─ index.js
└─ sub/
   ├─ index.html
   └─ index.js
```

What I get instead is:
```
dist/
├─ index-[hash1].html
├─ index-[hash2].html
├─ index.js (Contents are `module.exports = './index-[hash1].html'`
├─ sub/
│  └─ index.js (Contents are `module.exports = '../index-[hash2].html'`
└─ esm/
   └─ index.js (Contents are the top level index.js, the sub/index.js contents are just gone, probably overridden)
```

I'm okay with the hashes (as long as it's consistent), but it looks like it's not doing things relative to the outdir per the "lowest common ancestor" rule outlined in the [esbuild documentation](https://esbuild.github.io/api/#outdir). And them it seems to be just completely overriding some files.

Admittedly, I'm pretty new to esbuild. I could me misconfiguring things. Would love some direction if I'm missing something.

**Comment by edoardocavazza** [comment]
Hello @ksmithut, thanks for reaching out. I can confirm that it was an unhandled case, but with it should be fixed now with the v0.11.20 release!

Thank you and let me know if it fixed the bug!

**Comment by ksmithut** [comment]
It does appear to work when I have two html entrypoints, but now if I only have one, it puts the `esm/` folder outside of my configured `outdir` option

**Comment by ksmithut** [comment]
Yes, it seems to be working as expected in the build :) Maybe this warrants a separate issue, but is there an example of how to use this plugin with `esbuild.serve()`? It appears that in the example above, it's serving the `index.html` with the link to the `index.js` without the `esm/` prefix, so it's not finding the assets properly.

**Comment by edoardocavazza** [comment]
Hi @ksmithut, we (still) dont use esbuild as dev server, but I will give it a look!
