### ISSUE TITLE
wtr-mocha-reporter (reportBrowserLogs.js) - missing dependencies @chialab/rna-logger in package

### ISSUE THREAD

**Issue by oscarmarina** [chialab/rna#26]
https://github.com/chialab/rna/blob/main/packages/wtr-mocha-reporter/lib/reportBrowserLogs.js

import { colors } from '@chialab/rna-logger';

@chialab/rna-logger

**Comment by edoardocavazza** [comment]
Thanks for reporting! I have replaced the logger import with the bare `chalk` module and updated the dependencies list accordingly.
