### ISSUE TITLE
esbuild-plugin-html does not support font file ttf

### ISSUE THREAD

**Issue by connorjclark** [chialab/rna#27]
Perhaps I'm overlooking an existing option? My expectation is that this would just be copied over to the assets build folder, just like any other asset.

```
src/client/styles/main.css:8:11: error: No loader is configured for ".ttf" files: src/client/fonts/VT323.ttf
    8 │   src: url('../fonts/VT323.ttf') format('truetype');
```

**Comment by edoardocavazza** [comment]
Hello! CSS references are handle by the core esbuild transformation, not by the HTML plugin. You have to configure esbuild to [treat font files with the `file` loader](https://esbuild.github.io/content-types/#external-file), or maybe you want to give [@chialab/esbuild-plugin-any-file](https://www.npmjs.com/package/@chialab/esbuild-plugin-any-file) a try!

**Comment by connorjclark** [comment]
Thank you for the guidance! Totally new to esbuild. Appreciate the help :)
