### ISSUE TITLE
Environment variables with non alphanumeric characters breaks esbuild

### ISSUE THREAD

**Issue by Unnoen** [chialab/rna#29]
In es-plugin-env, if an environment variable contains symbols, `CommonProgramFiles(x86)` for example, esbuild throws an error.

`error: The define key "process.env.CommonProgramFiles(x86)" contains invalid identifier "CommonProgramFiles(x86)"`

```
Error: Build failed with 2 errors:
error: The define key "process.env.CommonProgramFiles(x86)" contains invalid identifier "CommonProgramFiles(x86)"
error: Cannot read properties of undefined (reading 'errors')
    at failureErrorWithLog (D:\Code\Test\esbuild test\node_modules\esbuild\lib\main.js:1494:15)
    at D:\Code\Test\esbuild test\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The define key "process.env.CommonProgramFiles(x86)" contains invalid identifier "CommonProgramFiles(x86)"'
    }
]
```
I believe this is the root of the issue:
https://github.com/chialab/rna/blob/5a1edb5226eb6582cfc846d1fc25ed6bd41b5e04/packages/esbuild-plugin-env/lib/index.js#L5-L19

**Comment by edoardocavazza** [comment]
Closing this since the problem should have been addressed and we have not received any further notice.
