### ISSUE TITLE
Externals for HTML ESBuild plugin

### ISSUE THREAD

**Issue by martpie** [chialab/rna#34]
I am writing an application in Electron and I need to set externals to some names of Node.js native modules.

Is there any reason why externals is set to `[]` here? https://github.com/chialab/rna/blob/3544f2cd21507ea7688bbdc00a8aded16901015f/packages/esbuild-plugin-html/lib/index.js#L203

Is it something we could override via an option?

**Comment by edoardocavazza** [comment]
In the latest version (v0.14.10) we does not reset `externals` in html plugin. Would you have a try and tell me if everything works as expected?

**Comment by martpie** [comment]
I'm getting another issue with defining the name of the output file, but the externals problem is solved, thanks!
