### ISSUE TITLE
Option to specify output folder name for @chialab/esbuild-plugin-html

### ISSUE THREAD

**Issue by jasonwilliams** [chialab/rna#35]
Hey, great plugin.

There's just one issue for us, currently the exported folders are hardcoded to `iife` or `esm`.
We need our assets folder to have a specific name, is it possible to offer an override for this?

So instead of `dist/iife/index.js` we can have `dist/assets/index.js` (plus same in the index.html also)

**Comment by edoardocavazza** [comment]
Hello @jasonwilliams!

The problem with a common output dir is that we are running two separate esbuild runs and there is the possibility that some chunks will be overridden. Anyway, we can add two plugin options, something like `modulesOutdir` and `scriptsOutdir`, and you can try to set the same value in here.

**Comment by jasonwilliams** [comment]
@edoardocavazza that would be helpful thanks

**Comment by martpie** [comment]
So I have just faced an interesting issue while trying to import a PNG with the file loader. `app.html` being at the root of the out dir, my PNG was imported in `./iife/`, but ESBuild would say the PNG is on `./placeholder.png` instead of `./iife/placeholder.png`, hence breaking the URI for the file

**Comment by jasonwilliams** [comment]
> So I have just faced an interesting issue while trying to import a PNG with the file loader. `app.html` being at the root of the out dir, my PNG was imported in `./iife/`, but ESBuild would say the PNG is on `./placeholder.png` instead of `./iife/placeholder.png`, hence breaking the URI for the file.
> 
> Shouldn't static assets be imported at the same level as `app.html`? We don't need duplicate images for both builds.
> 
> _edit: my config:_
> 
> ```
> {
>   ...
>   loader: {
>     '.eot': 'file',
>     '.woff': 'file',
>     '.woff2': 'file',
>     '.svg': 'file',
>     '.ttf': 'file',
>     '.png': 'file',
>   },
> }
> ```

@martpie i think you’re describing a separate issue to what’s in this thread. It might be worth starting a new one to not muddy the waters here. Being able to rename the folders wouldn’t solve your problem

**Comment by jasonwilliams** [comment]
@edoardocavazza i saw you reference this issues in your PR. Have you now provided a way to specify the folder name now?

**Comment by jasonwilliams** [comment]
Resolved by https://github.com/chialab/rna/issues/43#issuecomment-1059268839
