### ISSUE TITLE
types are missing in the source code

### ISSUE THREAD

**Issue by upupming** [chialab/rna#41]
Hi there, thanks for the great plugins, they help me a lot.

Although the types are published in the npm registry, it is ignored in the source code. Could you please add it here too? Thanks!

https://github.com/chialab/rna/blob/5e26622d437a052121220116891492c44496b12b/.gitignore#L4

**Comment by edoardocavazza** [comment]
Hello!

Typescript should automatically import types from JS sources since we are using the `"checkJs": true` flag, aren't they working for you?

**Comment by upupming** [comment]
Thanks very much for your help, and it was my bad, I did not know `tsc` can generate JS Doc types definition too. No problems now! Thanks for your great contribution!
