### ISSUE TITLE
Could not find MIME for Buffer <null>

### ISSUE THREAD

**Issue by elite0226** [chialab/rna#46]
```
await esbuild
    .build({
      entryPoints: [`${outdir}/index.html`],
      outdir: outdir,
      minify: true,
      sourcemap: false,
      bundle: true,
      write: true,
      plugins: [
        htmlPlugin({
          // scriptsTarget: "es6",
          // modulesTarget: "es2020",
        }),
      ],
      assetNames: "[name]",
    })
```

After running the script, I got follow error:
![image](https://user-images.githubusercontent.com/50171204/163370944-c0800d78-c35c-44dd-8c1f-102d87f8ce4a.png)

**Comment by edoardocavazza** [comment]
Hello @elite0226,

I am not sure to understand the use case. The error occurs because the plugin cannot find the `index.html` source file.
Is ``${outdir}/index.html`` the correct path?
